rework pinning

diff --git a/bin/qmp-send b/bin/qmp-send
--- a/bin/qmp-send
+++ b/bin/qmp-send
@@ -1,5 +1,34 @@
 #!/bin/bash
-SOCKET=$1
+SCRIPT_DIR=$(dirname $(readlink -f $0))
+source $SCRIPT_DIR/config-common
+source $SCRIPT_DIR/config-machine
+
+WANT_SEAT=$(echo $1 | cut -d":" -f 2)
+WANT_MACHINE=$(echo $1 | cut -d":" -f 1)
+
+MACHINE=${WANT_MACHINE:-"default"}
+SEAT=${WANT_SEAT:-"$MACHINE"}
+
+
+if [ "x$MACHINE" == "x" ]; then
+	echo "Usage:"
+	echo "$0 [machine-name]"
+	exit 3
+fi
+
+if [ ! -d "$MACHINE_PATH" ]; then
+	echo "Machine $MACHINE does not exists"
+	echo "Reason: $MACHINE_PATH does not exist"
+	exit 1
+fi
+
+if [ ! -e "$MACHINE_PATH/config" ]; then
+	echo "Can't load $MACHINE"
+	echo "Reason: 'config' does not exist in $MACHINE_PATH"
+	exit 2
+fi
+
+
 shift
 
-printf '{ "execute": "qmp_capabilities" } %s' "$@" | nc -U -w 3 "$SOCKET" 
+printf '{ "execute": "qmp_capabilities" } %s' "$@" | nc -U -w 3 "$SOCKET_QMP" 
